<script setup>
import { computed, ref, watch } from 'vue'
import { themeFor, themeKeys, themeVariables } from '../theme/restaurantThemes'
const props = defineProps({ modelValue: { type: String, default: 'modern' }, primaryColor: { type: String, default: '' }, disabled: Boolean })
const emit = defineEmits(['update:modelValue', 'update:primaryColor'])
function storedColors() { try { return JSON.parse(localStorage.getItem('menuos_recent_theme_colors') || '[]') } catch { return [] } }
const recentColors = ref(storedColors())
const previewDevice = ref('mobile')
const previewStyle = computed(() => themeVariables(props.modelValue, props.primaryColor || null))
function select(key) { emit('update:modelValue', key); emit('update:primaryColor', '') }
function reset() { emit('update:primaryColor', '') }
function updateColor(color) { if (!/^#[0-9a-f]{6}$/i.test(color)) return; emit('update:primaryColor', color) }
watch(() => props.primaryColor, (color) => { if (!color) return; recentColors.value = [color, ...recentColors.value.filter((item) => item !== color)].slice(0, 6); localStorage.setItem('menuos_recent_theme_colors', JSON.stringify(recentColors.value)) })
</script>
<template><div class="theme-selector"><div class="theme-options" role="radiogroup" :aria-label="$t('themes.choose')"><button v-for="key in themeKeys" :key="key" class="theme-card" :class="{ selected: modelValue === key }" type="button" role="radio" :aria-checked="modelValue === key" :aria-label="`${$t(`themes.${key}`)} · ${$t(`themes.descriptions.${key}`)}${modelValue === key ? ` · ${$t('themes.selected')}` : ''}`" :disabled="disabled" @click="select(key)"><span class="theme-swatch" :style="themeVariables(key)"><i /><i /><i /></span><strong>{{ $t(`themes.${key}`) }}</strong><small>{{ $t(`themes.descriptions.${key}`) }}</small></button></div><div class="preview-device-switcher" :aria-label="$t('themes.previewSize')"><button v-for="device in ['mobile', 'tablet', 'desktop']" :key="device" type="button" :class="{ active: previewDevice === device }" @click="previewDevice = device">{{ $t(`themes.${device}`) }}</button></div><div class="theme-preview-frame" :class="`is-${previewDevice}`"><div class="theme-live-preview" :style="previewStyle"><span>{{ $t('themes.preview') }}</span><strong>MenuOS</strong><div class="preview-dishes"><i /><i /><i /></div><button type="button">{{ $t('common.save') }}</button></div></div><div class="color-override"><label>{{ $t('themes.customColor') }}<input :value="primaryColor || themeFor(modelValue).primary" type="color" :disabled="disabled" @input="updateColor($event.target.value)"></label><label>HEX<input class="hex-input" :value="primaryColor || themeFor(modelValue).primary" maxlength="7" :disabled="disabled" @change="updateColor($event.target.value)"></label><div v-if="recentColors.length" class="recent-colors" :aria-label="$t('themes.recentColors')"><button v-for="color in recentColors" :key="color" type="button" :style="{ background: color }" :aria-label="$t('themes.useColor', { color })" @click="updateColor(color)" /></div><button class="button button-secondary" type="button" :disabled="disabled || !primaryColor" @click="reset">{{ $t('themes.reset') }}</button></div></div></template>
